### PR TITLE
fix: remove playing nodes from destruction

### LINKED ISSUE #400: `AudioNode` is garbage collected even it is connected with another node.
### Description

Though it is hard to suggest a code to reproduce,
I've experienced `AudioBufferSourceNode` is garbage collected and stop playing (by being `~AudioNode()` is called)

For example,

```ts
const context = new AudioContext();
{
  const sourceNode = context.createBufferSourceNode();
  sourceNode.buffer = myBuffer;
  sourceNode.connect(context.destination);
  sourceNode.start();
}
```

In this code, `sourceNode` should not be garbage collected since it is connected with `AudioContext.destination`, but `sourceNode` can be garbage collected thus `sourceNode` is cleaned up, finally disconnected from `AudioContext`.

### Steps to reproduce

_

### Snack or a link to a repository

_

### React Native Audio API version

4ccd750

### React Native version

0.75.3

### Platforms

iOS, Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by mdydek**
Closes #400 
Closes RNAA-62

## Introduced changes

- added checks during destruction in order not to destroy playing source nodes

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [x] Added/Conducted relevant tests
- [x] Performed self-review of the code
- [ ] Updated Web Audio API coverage
- [ ] Added support for web

### CODE REVIEW

**Review by maciejmakowski2003 — APPROVED** [review]
Great work! Before merge please check if it works well on drums example with bpm set to 1000.

**Review by michalsek — APPROVED** [review]
Good job! 🔥

**Comment by mdydek** [comment]
Unfortunately previous approach using dynamic cast turned out to be not efficient enough in stressful environment.

File: packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.h [hunk 1]
```diff
@@ -46,6 +49,7 @@ class AudioNodeManager {
       audioNodesToConnect_;
 
   void settlePendingConnections();
+  void cleanupNode(const std::shared_ptr<AudioNode> &node);
```
Comment (maciejmakowski2003) [inline packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.h:52]: Where it is used?

Comment (mdydek) [reply packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.h:52]: In AudioNodeManager.cpp to not repeat lines: 
  nodeDeconstructor_.addNodeForDeconstruction(node);
  node.get()->cleanup();

**Review by maciejmakowski2003 — APPROVED** [review]

File: packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp [hunk 2]
```diff
@@ -51,7 +51,7 @@ void OscillatorNode::processNode(
 
   updatePlaybackInfo(processingBus, framesToProcess, startOffset, offsetLength);
 
-  if (!isPlaying()) {
+  if (!isPlaying() && !isStopScheduled()) {
```
Comment (michalsek) [inline packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp:54]: wont it cause the oscillator to immediately stop playing once it is scheduled?

Comment (mdydek) [reply packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp:54]: from my understanding `stopScheduled` is a state where the time of finishing playing is set but it is yet to come, so practically `stopScheduled` state is also kind of playing state @maciejmakowski2003

Comment (michalsek) [reply packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp:54]: oh wait, didn't notice the `!`

buut I've followup question why this condition is needed? I can understand it as
"is not playing and stop is not scheduled" while I don't see a reason why it would be in the state where it is not playing and stop is scheduled 🤔

Comment (mdydek) [reply packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp:54]: It IS playing in both of states, but in plain playing state we don’t know the time of ending. It was introduced by @maciejmakowski2003, because he needed differentiation in some of his features.

**Comment by michalsek** [comment]
Good to go! :)

File: packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp (hunk 2 above)
Comment (maciejmakowski2003) [reply packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp:54]: Exactly like @mdydek explained. I have introduced new state of ASSN while refactoring frame accurate stop. We need to know if node is playing and stop is scheduled to happen or it is not.
